# Generated by Django 6.1.1 on 2026-09-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimentacao_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
    ]
