# Generated by Django 6.1.1 on 2026-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimentacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='doador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doador'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_donativo',
            field=models.BooleanField(default=False, verbose_name='É donativo?'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade',
            field=models.CharField(choices=[('litro', 'Litro'), ('metro', 'Metro'), ('quilo', 'Quilo'), ('peça', 'Peça')], max_length=20, verbose_name='Unidade'),
        ),
    ]
