# Generated by Django 6.1.1 on 2026-09-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0002_equipe_praia'),
        ('praia', '0003_praia_cadastrado_por_praia_dt_cadastro'),
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id_acao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MUTIRAO', 'Mutirão'), ('COLETA_VOLUNTARIA', 'Coleta voluntária')], max_length=30)),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, default='', max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('imagens', models.JSONField(blank=True, default=list)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_ultima_edicao', models.DateTimeField(blank=True, null=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_cadastradas', to='usuario.usuario')),
                ('praia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='praia.praia')),
                ('ultimo_editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_editadas', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'db_table': 'acao',
                'ordering': ('-data', 'horario'),
            },
        ),
        migrations.CreateModel(
            name='AcaoEquipe',
            fields=[
                ('id_acao_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_vinculadas', to='acao.acao')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_vinculadas', to='equipe.equipe')),
            ],
            options={
                'verbose_name': 'Equipe da ação',
                'verbose_name_plural': 'Equipes da ação',
                'db_table': 'acao_equipe',
                'unique_together': {('acao', 'equipe')},
            },
        ),
        migrations.CreateModel(
            name='AcaoParticipante',
            fields=[
                ('id_acao_participante', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('RECUSADO', 'Recusado'), ('PRESENTE', 'Presente'), ('NAO_COMPARECEU', 'Não compareceu')], default='PENDENTE', max_length=20)),
                ('compareceu', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, default='')),
                ('dt_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='acao.acao')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_participadas', to='usuario.voluntario')),
            ],
            options={
                'verbose_name': 'Participante da ação',
                'verbose_name_plural': 'Participantes da ação',
                'db_table': 'acao_participante',
                'unique_together': {('acao', 'voluntario')},
            },
        ),
        migrations.CreateModel(
            name='AcaoResponsavel',
            fields=[
                ('id_acao_responsavel', models.AutoField(primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('COORDENADOR', 'Coordenador'), ('RESPONSAVEL', 'Responsável')], default='RESPONSAVEL', max_length=20)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='acao.acao')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_responsavel', to='usuario.voluntario')),
            ],
            options={
                'verbose_name': 'Responsável pela ação',
                'verbose_name_plural': 'Responsáveis pela ação',
                'db_table': 'acao_responsavel',
                'unique_together': {('acao', 'voluntario')},
            },
        ),
    ]
