# Generated by Django 6.1.1 on 2026-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='cadastrado_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='cadastrado_por_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='ultimo_editado_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='ultimo_editado_por_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
