# Generated by Django 6.1.1 on 2026-09-19 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0002_acao_cadastrado_por_nome_acao_cadastrado_por_tipo_and_more'),
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoParticipanteHistorico',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('RECUSADO', 'Recusado'), ('PRESENTE', 'Presente'), ('NAO_COMPARECEU', 'Não compareceu')], max_length=20)),
                ('compareceu', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, default='')),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('movido_por_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('movido_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_participantes', to='acao.acao')),
                ('movido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_participantes_movidos', to='usuario.usuario')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_acoes_participadas', to='usuario.voluntario')),
            ],
            options={
                'verbose_name': 'Histórico de participante da ação',
                'verbose_name_plural': 'Histórico de participantes da ação',
                'db_table': 'acao_participante_historico',
                'ordering': ('-dt_movimentacao', 'voluntario__nome'),
            },
        ),
    ]
