# Generated by Django 6.1.1 on 2026-09-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0003_acaoparticipantehistorico'),
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoparticipantehistorico',
            name='restaurado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acaoparticipantehistorico',
            name='restaurado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acaoparticipantehistorico',
            name='restaurado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_participantes_restaurados', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='acaoparticipantehistorico',
            name='restaurado_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='acaoparticipantehistorico',
            name='restaurado_por_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
