# Generated by Django 6.1.1 on 2026-09-20 02:53

import acao.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0004_acaoparticipantehistorico_restaurado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoImagem',
            fields=[
                ('id_acao_imagem', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to=acao.models.caminho_imagem_acao)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_acao', to='acao.acao')),
            ],
            options={
                'verbose_name': 'Imagem da ação',
                'verbose_name_plural': 'Imagens da ação',
                'db_table': 'acao_imagem',
                'ordering': ('-dt_cadastro',),
            },
        ),
    ]
