# Generated by Django 6.1.1 on 2026-09-22 00:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('praia', '0003_praia_cadastrado_por_praia_dt_cadastro'),
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id_condominio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('responsavel_nome', models.CharField(max_length=150)),
                ('responsavel_telefone', models.CharField(max_length=20)),
                ('responsavel_email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('porte', models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande')], default='MEDIO', max_length=20)),
                ('confiabilidade', models.CharField(choices=[('EM_AVALIACAO', 'Em avaliação'), ('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='EM_AVALIACAO', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por_nome', models.CharField(blank=True, max_length=150)),
                ('dt_ultima_edicao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_editado_por_nome', models.CharField(blank=True, max_length=150)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condominios_cadastrados', to='usuario.usuario')),
                ('praia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condominios', to='praia.praia')),
                ('ultimo_editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condominios_editados', to='usuario.usuario')),
            ],
            options={
                'db_table': 'condominio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id_bag', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('CHEIA', 'Cheia'), ('RETIRADA', 'Retirada'), ('EM_TRANSITO', 'Em trânsito'), ('ENTREGUE', 'Entregue à ONG'), ('DANIFICADA', 'Danificada'), ('PERDIDA', 'Perdida')], default='DISPONIVEL', max_length=20)),
                ('peso_atual_kg', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentual_ocupacao', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observacoes', models.TextField(blank=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por_nome', models.CharField(blank=True, max_length=150)),
                ('dt_ultima_edicao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_editado_por_nome', models.CharField(blank=True, max_length=150)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bags_cadastradas', to='usuario.usuario')),
                ('ultimo_editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bags_editadas', to='usuario.usuario')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bags', to='condominio.condominio')),
            ],
            options={
                'db_table': 'bag',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoBag',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTREGA_CONDOMINIO', 'Entrega ao condomínio'), ('INICIO_USO', 'Início de uso'), ('REGISTRO_CHEIA', 'Registro de bag cheia'), ('RETIRADA', 'Retirada do condomínio'), ('ENVIO_ONG', 'Envio para a ONG'), ('RECEBIMENTO_ONG', 'Recebimento pela ONG'), ('DANO', 'Registro de dano'), ('PERDA', 'Registro de perda'), ('OUTRO', 'Outro')], max_length=30)),
                ('status_anterior', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('CHEIA', 'Cheia'), ('RETIRADA', 'Retirada'), ('EM_TRANSITO', 'Em trânsito'), ('ENTREGUE', 'Entregue à ONG'), ('DANIFICADA', 'Danificada'), ('PERDIDA', 'Perdida')], max_length=20)),
                ('status_novo', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('CHEIA', 'Cheia'), ('RETIRADA', 'Retirada'), ('EM_TRANSITO', 'Em trânsito'), ('ENTREGUE', 'Entregue à ONG'), ('DANIFICADA', 'Danificada'), ('PERDIDA', 'Perdida')], max_length=20)),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('registrado_por_nome', models.CharField(max_length=150)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='condominio.bag')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_bag_registradas', to='usuario.usuario')),
            ],
            options={
                'db_table': 'movimentacao_bag',
                'ordering': ['-data_movimentacao', '-id_movimentacao'],
            },
        ),
    ]
