# Generated by Django 6.1.1 on 2026-09-22 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaControle',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('entidade', models.CharField(choices=[('CONDOMINIO', 'Condomínio'), ('BAG', 'Bag'), ('MOVIMENTACAO', 'Movimentação de bag')], max_length=20)),
                ('id_registro', models.PositiveIntegerField()),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('MUDANCA_STATUS', 'Mudança de status'), ('MOVIMENTACAO', 'Registro de movimentação')], max_length=20)),
                ('usuario_nome', models.CharField(max_length=150)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('resumo', models.CharField(max_length=255)),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_novos', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_controle', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Auditoria do controle',
                'verbose_name_plural': 'Auditorias do controle',
                'db_table': 'auditoria_controle',
                'ordering': ['-data_evento', '-id_auditoria'],
            },
        ),
    ]
