# Generated by Django 6.1.1 on 2026-09-18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praia',
            fields=[
                ('id_praia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('praia_ativa', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='praias_cadastradas', to='usuario.usuario')),
                ('cadastrado_por_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('cadastrado_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('ultimo_editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='praias_editadas', to='usuario.usuario')),
                ('ultimo_editado_por_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('ultimo_editado_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_ultima_edicao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Praia',
                'verbose_name_plural': 'Praias',
                'db_table': 'praia',
            },
        ),
    ]
