# Generated by Django 6.1.1 on 2026-09-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praia',
            fields=[
                ('id_praia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('praia_ativa', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Praia',
                'verbose_name_plural': 'Praias',
                'db_table': 'praia',
            },
        ),
    ]
