# Generated by Django 6.1.1 on 2026-09-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0002_alter_praia_latitude_alter_praia_longitude'),
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
    ]
