# Generated by Django 6.1.1 on 2026-09-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0002_alter_praia_latitude_alter_praia_longitude'),
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='praia',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='praias_cadastradas', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='praia',
            name='dt_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
