# Generated by Django 6.1.1 on 2026-09-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='auditoria_e_entidad_ff160b_idx',
            old_name='auditoria_e_entidad_8d2c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='auditoria_e_data_ev_ee8a96_idx',
            old_name='auditoria_e_data_ev_0b4a96_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='auditoria_e_usuario_feee63_idx',
            old_name='auditoria_e_usuario_3d442a_idx',
        ),
    ]
