# Generated by Django 6.1.1 on 2026-09-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_voluntario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('dt_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PAUSADO', 'Pausado')], default='ATIVO', max_length=20)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'db_table': 'voluntario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDENADOR', 'Coordenador')], max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('id_voluntario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.voluntario')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
    ]
