# Generated by Django 6.1.1 on 2026-09-18 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_voluntario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('dt_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PAUSADO', 'Pausado')], default='ATIVO', max_length=20)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'db_table': 'voluntario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDENADOR', 'Coordenador')], max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('id_voluntario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuario.voluntario')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_cadastrados', to='usuario.usuario')),
                ('dt_cadastro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('dt_ultima_edicao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_editados', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='voluntario',
            name='ultimo_editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios_editados', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='dt_ultima_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios_cadastrados', to='usuario.usuario'),
        ),
    ]