# Generated by Django 6.1.1 on 2026-09-19 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_audit_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('cadastrado_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('ultimo_editado_por_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('ultimo_editado_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_ultima_edicao', models.DateTimeField(blank=True, null=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_cadastradas', to='usuario.usuario')),
                ('ultimo_editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_editadas', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'db_table': 'equipe',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='EquipeMembro',
            fields=[
                ('id_equipe_membro', models.AutoField(primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('VOLUNTARIO', 'Voluntário'), ('COORDENADOR', 'Coordenador')], default='VOLUNTARIO', max_length=15)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('dt_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_saida', models.DateTimeField(blank=True, null=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('cadastrado_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('ultimo_editado_por_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('ultimo_editado_por_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_ultima_edicao', models.DateTimeField(blank=True, null=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_equipe_cadastrados', to='usuario.usuario')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='equipe.equipe')),
                ('ultimo_editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_equipe_editados', to='usuario.usuario')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='usuario.voluntario')),
            ],
            options={
                'verbose_name': 'Membro da equipe',
                'verbose_name_plural': 'Membros da equipe',
                'db_table': 'equipe_membro',
                'ordering': ('equipe', 'voluntario'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ATIVO')), fields=('equipe', 'voluntario'), name='unico_membro_ativo_por_equipe')],
            },
        ),
    ]
