# Generated by Django 6.1.1 on 2026-09-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('praia', '0003_praia_cadastrado_por_praia_dt_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='praia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='praia.praia'),
        ),
    ]
